### ISSUE TITLE
Background image in the bad world (replace static white circle by car)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#106]
@gabrielabila 

This need to be discussed but I think the white static dot should be removed form the static bad world image, it's confusing as they don't move and they are not using the same graphology.

Let's discuss this together it's a detail

**Comment by agrignard** [comment]
@gabrielabila if you want to make a version replacing the circle by the cars here is the image
https://github.com/CityScope/CS_Cooper-Hewitt/tree/master/ABMobility/data/image/glyphs

**Comment by gabrielabila** [comment]
@agrignard, which of these images is the final car version? The "car.gif" is an older version we are not using. Today, when you guys showed me the table in the video call, it loked like it's still the round PEV icon, but there's nothing like that in this link.

**Comment by agrignard** [comment]
Yes we use this one as a gif but I don't have a better resolution (it's a pixel car)
https://github.com/CityScope/CS_Cooper-Hewitt/blob/master/ABMobility/data/image/glyphs/car.gif

`````
carGlyph[0] = loadImage("image/glyphs/car.gif");
`````

**Comment by gabrielabila** [comment]
@agrignard, I've just added 2 new versions of the BAD world streets, one with no cars and another with pixel cars. See if they work!

https://github.com/CityScope/CS_Cooper-Hewitt/tree/master/ABMobility/data/image/background

**Comment by agrignard** [comment]
Thanks!! For now I put the image without car to be sure that when we see a car or a bike or a ped it's coming from the simulation. There is always the option to reput also the car witht he pixel now if needed
