### ISSUE TITLE
First surface Mirror sizes

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#11]
Size of the first surface Mirror is needed, so it can be ordered.

**Comment by yasushisakai** [comment]
was this ordered?

**Comment by LAAP** [comment]
The dimensions are 31x45cm. We found the online shop; (https://firstsurfacemirror.com/glass-first-surface-mirror/) but it is not in Amazon, so Carson needs to talk with Mary....

**Comment by Carsonsmuts** [comment]
Correct, I cannot order using the card.

I’ll chat to her on Monday, I have to talk to Mary about Unity3D quote anyway.

C

**Comment by LAAP** [comment]
Awesome! Thanks! I can be with you going through this "Intense experience"

**Comment by yasushisakai** [comment]
related to #22

**Comment by Carsonsmuts** [comment]
Lets order all the mirrors in one shot.

**Comment by agrignard** [comment]
Duplicate of #56
