### ISSUE TITLE
PEVs instead of cars at the good world

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#110]
In the good world we should avoid having cars: Please, change the car pixel-art for a PEV-like pixel-art

**Comment by agrignard** [comment]
one quick visual way to fix it in  https://github.com/CityScope/CS_Cooper-Hewitt/commit/a1d133ebc5d91295cd458cc36e4cba266094f5e5

We might make the image a bit bigger

@yasushisakai is it easy/doable?

We have to keep in mind that here we just update the aspect of the car but it is still a car in the simu.
