### ISSUE TITLE
Autotune and Amplification without computing

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#112]
This is a last minisecond request (that was anticipated for a while but now we have to face it)

The data driven approach was clearly not the good choice for a museum approach as it is very hard to see the dynamic on the table in term of density, flow of people, etc  what we have, as predicted, is a very smart noise... and we finally realize this one day before the end

Just to be clear at this time of the deployment there is unfortunately very few that can be done.

However one last chance (and pretty safe as it doesn't impact on the code) is to test the following:

Regenerate the simPop.csv with some more extreme value in the block. Replacing the low value from 25 to 10 or even lower and the high value from 100 to 200 (can we go bigger than 100 or is it the top?). 

Some question here for @doorleyr and @aberke :

1. What is the real input for the algo that generate simPop.csv in the documentation it linked to this spreadsheet:
https://docs.google.com/spreadsheets/d/1aKRPp83EWWdBri6MwjuGcZVSki2xQuxd_OjMAdrrpS4/edit#gid=919292076

However this spreadsheet is different form (which was suppose to be the same)
https://github.com/CityScope/CS_Cooper-Hewitt/blob/master/ABMobility/data/block/Cooper%20Hewitt%20Buildings%20-%20Building%20Blocks.csv

Just compare the 2 first building to see that there are not the same. 

2. Why we  only have 3 buildings having working places?

Also is the wiki is up to date? Can we safely regenerate a simPopAmplified.csd from a blockAmplified.csv?

Whoever is reading this issue is more than welcome to help (first by creating  the blockAmplified.csv with the more extreme value) being sure it's coherent with the size of the physical building @LAAP and @guadalupebabio maybe you can help on that?

**Comment by guadalupebabio** [comment]
Both csv are the same, but the one in google is in a different layer. @yasushisakai is taking care if changing the intensity for low and high

**Comment by yasushisakai** [comment]
@agrignard I know were to change, if I have time to setup the dependicies.

**Comment by aberke** [comment]
@yasushisakai does that mean you have this handled and @doorleyr and I should wait?
I'm a little unclear on the request/issue.

**Comment by agrignard** [comment]
rephrase in #115
