### ISSUE TITLE
Unity Slider line offset

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#119]
The unity slider line is not aligned with the Slider and the Simulation one

**Comment by guadalupebabio** [comment]
@popabczhang we will solve it today

**Comment by popabczhang** [comment]
fixed with the new start and end UI for slider offset at commit:
https://github.com/popabczhang/3d_projection_mapping_unity/commit/2ffb700023452945dcf3a8c89bd0488079844042
and release:
https://github.com/popabczhang/3d_projection_mapping_unity/releases/tag/1.0
