### ISSUE TITLE
Unity Empire State

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#120]
@guadalupebabio is working in it but might need some helps from @popabczhang 

The empire state rendering is not matching (something like a rotation of 90 or -90)

**Comment by guadalupebabio** [comment]
I have emailed @popabczhang, we will try to solve it today

**Comment by popabczhang** [comment]
check with @guadalupebabio, no error in Unity.
will fix with the physical tag.
