### ISSUE TITLE
Good Computer not running

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#121]
9am this morning status

Bad computer: working
Good Computer: Not working (it's on but it seems that the script didn't start)

I keep it as it is so @yasushisakai can see the status

**Comment by yasushisakai** [comment]
Inspecting this. 
Reason: for some reason .sh extension files use “VS Code” to open.
@RELNO I might uninstall Code, is this fine?

**Comment by RELNO** [comment]
@yasushisakai sure, keep in mind VS [full version] is also there and might have similar behavior.

**Comment by yasushisakai** [comment]
Changed “.sh” files to be opened by the terminal.
Checked it three times in a row, and it ran.

@RELNO Thanks for the note! That might been the issue. Let’s see

I’ll keep this issue open until tomorrow morning.

**Comment by yasushisakai** [comment]
We will be doing a boot up torture test with @Carsonsmuts.
This will also test this feature too.

**Comment by yasushisakai** [comment]
Closing
