### ISSUE TITLE
Scanning format

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#14]
@RELNO and @yasushisakai 

Can we agree on the format of the string that will be send by the scanner

I think a simple validate json format is good (so we can also send it to cityIO and then explore a bit the difference between UDP and cityIO

The idea is to have a string with id and rot for now
Currentlt it's more or less this:
[-1, -1, -1, ["1","3"], -1, -1, -1, -1, ["21","2"], -1, -1, -1, -1, -1, -1, -1, -1, -1]

what about something like this (an array of 18 tuple representing id and rot):

`````
{ "0":"0", "1":"3", etc } 
`````

**Comment by RELNO** [comment]
Adding @popabczhang:
for now, JSON accepted strings [a list of list] are delivered over UDP in the following format:

`[['-1', '-1'], ['-1', '-1'], ['12', '3'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['1', '0'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1'], ['-1', '-1']]`

['T', 'R'] are types [0-23] and rotations [0,1,2,3 corresponds to 0,90,180,270] 
where [-1, -1] is null result.
CityIO has its own structure which, for the internal CH purposes might be redundant. Nevertheless, the UDP string is JSON, so cityIO won't reject it.

**Comment by agrignard** [comment]
Awesome!

https://github.com/CityScope/CS_Cooper-Hewitt/wiki/Scanning

**Comment by agrignard** [comment]
Well I was a bit to optimistic when closing this issue

Can we have a valid json? The one propose is not a valid json

**Comment by RELNO** [comment]
It should be ok per https://jsonlint.com/ if you `'`-->`"`, ergo:
`
[
  ["-1", "-1"],
  ["-1", "-1"],
  ["12", "3"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["1", "0"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"],
  ["-1", "-1"]
]
`

**Comment by agrignard** [comment]
yep so with " instead of ' it's valid

So we go for this one

**Comment by agrignard** [comment]
so can let's agree on something that work

We  need a key

So this is the format and the only one that need to be send 

````
{"grid":[[0,0],[1,2],........,[17,2]]}
`````

otherwise it's not an exact parsable JSON Object and it won't be cityIO compatible either and then we can potentially add the header, etc etc

**Comment by RELNO** [comment]
cityIO friendliness: https://cityio.media.mit.edu/api/table/ch
done in https://github.com/RELNO/CityScope_Scanner_Python/commit/15f4cbd1c395d7ed1a35baeb0497e87f784f84fc

`{
	"grid": [
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[19, 3],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[19, 3],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1],
		[-1, -1]
	]
}
`
