### ISSUE TITLE
Road Network generation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#15]
Generate 6 different graphs in https://github.com/CityScope/CS_Cooper-Hewitt/tree/master/ABMobility/data/network

3 graphs per world
Ped, bike, car

Actually we have 6 times the same graph

**Comment by yasushisakai** [comment]
This was assigned to @LAAP

**Comment by LAAP** [comment]
Cooking it!

**Comment by LAAP** [comment]
Here is the link to the graph of the "BAD_World":

https://www.dropbox.com/s/8gnrzz1r0t7xgcs/181019_Road_path_BAD.3dm?dl=0

-There are Car and Bike parking. 
-Each "path" has access to the buildings
-Each "path" has a link with the zombie-land world

It is in Rhino format. Let me know if you need it in other formats

The so-called "GOD_World" is on his way. Expected tonight. A bit more "fluid" and a bit F-crazy... We will see...

Cheers!

**Comment by yasushisakai** [comment]
Thanks @LAAP, I will generate the .geojson and come back to you.

**Comment by LAAP** [comment]
Hi, Here is the link to the first TEST of the road network:

https://www.dropbox.com/s/jp6f3ys09jqmuev/181022_Road_good_bad_T1.3dm?dl=0

My MIT Media Lab Rhino license has expired few hours before Members Week (Sad). Please Y can you do the mirror on the PED_GOOD and CAR_GOOD?

Thank you!

**Comment by yasushisakai** [comment]
[networks.zip](https://github.com/CityScope/CS_Cooper-Hewitt/files/2504175/networks.zip)

enjoy

**Comment by yasushisakai** [comment]
None of the networks seems to work...

There are two things that can cause this.

1. Disconnected Node
  if the nodes are not connected end to end, there is a change that the node cannot finds it path to anywhere. In Addition, other nodes that needs to use that node, cannot go to the final destination unless there is a detour that exist. The script that converts ```rhino -> geojson``` tries to define as one node if the distance between two are in some tolerance. (right now, it is 1mm)

2. Wrong direction
  If the network takes direction in account, and connected wrongly, that will effectively make an isolated node too.

**Comment by agrignard** [comment]
The current graph status is the following. In the current simulation to have something running everyone is then using the bike graph (looks weird but at least it runs)

car_1 crash
car_2 crash

bike_1 ok
bike_2 ok

ped_1 crash
ped_2 crash

**Comment by agrignard** [comment]
@yasushisakai and @LAAP one option could be to use GAMA to clean your graph. Depending one wht is the problem you are facing this model gives different tools to clean a dirty graph

if you want to have a look here is a model that clean road.shp file (availble in the library models of GAMA)

https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Features/Data%20Cleaning/models/Clean%20Line%20Network.gaml

**Comment by agrignard** [comment]
<img width="1920" alt="screen shot 2018-10-25 at 11 04 49" src="https://user-images.githubusercontent.com/3928502/47510281-d6a0b700-d845-11e8-983d-6ae7bc2c6b9a.png">

Gama is able to clean the messy graph. The only issue is that it's not ready yet to rexport it, as it suppose to use it in a GAMA simulation. 

I am working with one of my colleagues Patrick to try to implement this feature if no one find a better way to clean those graphs

**Comment by agrignard** [comment]
Ok so eveything work perfeclty in GAMA so I cannot understadn what is the problem with this graph it seems connected and valide. I even produce a valide one from GAMA and still processing doesn't want to run agent on top of it.

I have a strong feeling that some onf the small modif made in RoadNetwork (that seemed innocent introduces a very hard to debug software..)

**Comment by LAAP** [comment]
Hi, here it is the link to the new road graph:

https://www.dropbox.com/s/dp8ms1hjh7b2sxn/181026_road_path_S_clean.3dm?dl=0

I will try to debug at my side

**Comment by LAAP** [comment]
Link to the geoJSON:

https://www.dropbox.com/sh/zh5ivij9bzuqx2i/AAAhkWktkTSFFyoFw8x620ofa?dl=0

Made with: https://geoconverter.hsr.ch/

**Comment by agrignard** [comment]
I close this one also as it has been fix by providing 3 simple but working graphs. We will slowly iterate on the complexity of this graph but as it is the simualtion is working fine with the 3 current graph
