### ISSUE TITLE
[known issue] FrameRate slow because of PGraphic.get() function

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#16]
The frame rate is currently slow because of PGraphic.get() function when
stitching two ```Worlds``` together.

[reference](https://processing.org/reference/get_.html) talking about this.

we should (1) use the ```loadPixels() ,pixels[], updatePixels()``` for faster rendering, yet, (2) shaders (Examples>Topic>Shaders>ImageMask) might be even better.

**Comment by yasushisakai** [comment]
another weird behavior: the framerate increases when I set scale to 1

**Comment by yasushisakai** [comment]
recovered framerate.
Currently running 35-40fps 44989e82d322258a297a725bda962b3f0a25d6d5

cpu: Intel i7-7700HQ
gput: GeForece GTX 1060

closing, will return to speed optimization later.

**Comment by yasushisakai** [comment]
we have now over 50 using shaders.

**Comment by LAAP** [comment]
Question to @yasushisakai : Can the complexity of the road-graph impact in the FrameRate?

**Comment by yasushisakai** [comment]
@LAAP yes, it can. 
But I think we are not close to that, and I have few strategies to reduce it both on the rhino side and the simulation side to mitigate this.
