### ISSUE TITLE
Network edge class

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#21]
The Idea of having a network edge class if good.

- Provides a way to count congestion.
- (Might) help speedup shortest path calculation
- Could be used as an 'address' to have better collision detection

![networkedge](https://user-images.githubusercontent.com/1502180/47291184-b3b99d00-d5d0-11e8-984d-47238e705657.jpg)

The question/issue is around the fact that the ```Pathfinder``` object has a similar concept called ```Connectors```, which is listed in each ```Node```, pointing to the other ```Node```. How should ```Edges``` relate to ```Connectors```?

**Comment by yasushisakai** [comment]
(be aware this post will be used as my memo)

the strategy will be....
1. simplify the network
and then
2. intoduce the ```NetworkEdge``` class

**Comment by yasushisakai** [comment]
There seems to be no node found in initAgentInsideBuilding

**Comment by LAAP** [comment]
There should be, minimum 2 nodes per building.

**Comment by yasushisakai** [comment]
I don't think there will be time for this iteration. Reopen when we have time.
