### ISSUE TITLE
Simulation uses agent data from simPop.csv

### ISSUE THREAD

**Issue by aberke** [CityScope/CS_Cooper-Hewitt#28]
The submodule CityScope/CS_activityBased produces data for a simulation population.  This population has home and office locations and mobility motifs.  This data should be used to create the agents in the simulation.

There is now "dummy" data for a simulated population that uses 24 blocks and motifs with names composed of 
- "R" (residential) 
- "O" (office)
- "A" (amenity)

There data is at:
https://github.com/CityScope/CS_activityBased/blob/master/results/simPop.csv

@agrignard FYI

**Comment by yasushisakai** [comment]
sorry for being super picky

\-  "A" (residential)
\+ "A" (amenity)

?

**Comment by aberke** [comment]
Yes, thank you!  Updated.

**Comment by agrignard** [comment]
I am thinking on how to make the simulation ready to init agent from a SythPop.csv. However I don't understand right now what is the difference between the good and the bad world. right now if we assume that we want to initialise the agent from the SynthPop.csv it only give one configuration. What would be the difference between the 2 world? The mode that they are using? and if yes

**Comment by aberke** [comment]
From what we had talked about before with Ronan:
The only difference between the two worlds in terms of the agents, is the way they choose their mobility mode.
One of the outputs of the https://github.com/CityScope/CS_activityBased script is a function representing a mobility choice decision tree for an agent.
It is here: https://github.com/CityScope/CS_activityBased/blob/master/results/mode_choice.py

Ronan produced this with the idea that the mode choice for the agent is determined by the array of probabilities returned by this function.

| 0       | 1       | 2       | 3       |
|---------|---------|---------|---------|
| driving | cycling | walking | transit |

This function is based on real world data.
A different function with lower numbers for driving and higher numbers for cycling and walking would need to be used for the 'good/shared' world.

The idea was that this function would be copied into the simulation code.  
However, it seems like this needs to be tweaked because this function returns output for transit as a mobility mode, which the Cooper Hewitt simulation does not have.

**Comment by aberke** [comment]
I think the mobility choice for the agents is a slightly different conversation than producing the simulation agents from the CSV data, so I opened a new issue to track the discussion about the mobility choice function: https://github.com/CityScope/CS_Cooper-Hewitt/issues/41

**Comment by agrignard** [comment]
Initialization done in d48c690

Next step is #41
