### ISSUE TITLE
Documentation (Cooper Hewitt Requests)

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#3]
**CH** - They ask for:

"...we will need wiring diagrams for each project specifying how each part and cable will be connected as well as written guidance on how to assemble, operate, maintain, and troubleshoot in case of malfunction."

**CS** - We are not very good at documenting, but we will share our own material as soon as we have something. Probably, we will need to move the team to NY in order to work together with your Tech team at the deployment dates.

Issue: A documentation sharing system may be needed. Ideas?

**Comment by yasushisakai** [comment]
it will be optimal if we have everything in the wiki, but I think we should concentrate on making the thing first :)

@LAAP go ahead and reopen this issue if you think it needs to be visible.
