### ISSUE TITLE
Scanner latest version?

### ISSUE THREAD

**Issue by popabczhang** [CityScope/CS_Cooper-Hewitt#30]
@RELNO is the scanner submodule in this repo the latest?
When I run it, the sample points are not arranged like the Cooper-Hewitt table; the scanner is classifying 3 colors (black, white and red); and the format of the output data is not a valid json.
Please let me know if I am using the right version, thanks!

**Comment by RELNO** [comment]
No, latest is what master branch is @https://github.com/RELNO/CityScope_Scanner_Python
Per Yasushi, the submodule here will only be populated with releases, so for now it's only a placeholder

**Comment by RELNO** [comment]
@popabczhang I've just updated here to latest version of scanner, but IMO this is not really a sustainable path forward: The Scanner S/M might change several times an hour during calibrations, and we might skip updating the super-repo with all these changes, leaving everyone with a held-back commit. 
So for now, please make sure that when you pull, you use the Scanner, get it only from the master branch of Scanner origin repo, not from here. 
@yasushisakai @aberke is there a way to actually force track origin latest commit in submodule? In other words, can we make sure that if someone if doing `git clone --recursive` they only get the Scanner's master branch?

**Comment by yasushisakai** [comment]
we want the scanner submodle always pointing to the  ```HEAD``` of the scanner master, is this correct? I'm guessing we don't want to develop inside the repo (deleting submodules), to avoid a soup situation that it's all mixed up.

you will need a git-hooks on Scanner's side to
```git add Scanner```
```git commit -m 'sync with' ```
```git push -u origin master```
everytime we push to Scanner

This might seem better for know, but when we complete this project, I see my self forgetting to 
uninstall the githooks, therefor having the latest scanner that is not compatible with the other parts anymore..

**Comment by RELNO** [comment]
> we want the scanner submodle always pointing to the HEAD of the scanner master, is this correct? 

Yes, since Scanner commits are normally small and non-breaking, so it's ok pointing to `HEAD`.

> I see my self forgetting to uninstall the githooks

 [reminder](https://github.com/apps/reminders)?
