### ISSUE TITLE
Unity connection to scanning (through UDP)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#31]
Right now the Simulation part and the scanner are communicating together through UDP in order to know where the building are on the table.

One top priority will be to be able to update the unity display according to the information sent by the scanner

**Comment by yasushisakai** [comment]
@popabczhang can supplement info on this?

**Comment by popabczhang** [comment]
Unity repo is updated to be able to update the unity display according to the information sent by the scanner. To test, clone the latest commit of the unity repo and run the unity project in editor. Then run scanner to send json via UDP to unity via port 5006 (to avoid port conflict). Let me know if it doesn't work.

**Comment by agrignard** [comment]
@popabczhang if it's implementing and running on the table  I let you close this issue

**Comment by RELNO** [comment]
Connection was working well today, future issues on this should go into https://github.com/CityScope/CS_Cooper-Hewitt/issues/83
