### ISSUE TITLE
Road Network 2.0 update

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#32]
As far as we have:

- bike_1 (bike_bad)
- car_good

Working.

- car_1
- car_2
- bike_2
- ped_1
- ped_2

As placeholders

- bike_good
- car_bad
- ped_bad
- ped_good

Not working (In the process of cleaning).

**Comment by yasushisakai** [comment]
does every network have at least one node that is inside the building area??

**Comment by LAAP** [comment]
Of course!

**Comment by agrignard** [comment]
Here is the 2 world complete made of 3 different graphs. We can still iterate on those graph but I think the version 2.0 is there. Let's see later for the version 3.0 but this is not anymore the priority.

Well done Luis for the hard task and a big thank for the hidden worker Patrick from GAMA for the help on the cleaning graph (https://github.com/CityScope/CS_Cooper-Hewitt/tree/master/CH_GAMA)


@gabrielabila here is the 3 pictures 
<img width="1599" alt="bad" src="https://user-images.githubusercontent.com/3928502/47798105-0fd19f00-dcfe-11e8-8e16-7d69e9280553.png">
<img width="1597" alt="good" src="https://user-images.githubusercontent.com/3928502/47798106-0fd19f00-dcfe-11e8-83d8-78f92f3673fb.png">
<img width="1599" alt="good_and_bad" src="https://user-images.githubusercontent.com/3928502/47798107-106a3580-dcfe-11e8-85b4-c83ada8a82e7.png">

**Comment by agrignard** [comment]
ok so BAD NEWS I was to optimistic. The bike 2 is working better but I saw a crash after few minutes on the table....

**Comment by yasushisakai** [comment]
> Of course!

Good to know. Trying to minimize the network from a computation point of view. related to #21

**Comment by LAAP** [comment]
@agrignard Arnaud The demo with the graph is still running now. Maybe the Crash was coming from a different part of the code. Nocking on wood!

**Comment by yasushisakai** [comment]
has this been committed??

**Comment by yasushisakai** [comment]
(self replying for reference.)
yes, migration to the new network looks like has been settled at 389f7a7305c4c88b16f62fb376e69469f6863ee0

**Comment by LAAP** [comment]
This morning the processing was crashed.
