### ISSUE TITLE
[Oct 29 meeting follow up] permanent fixing of webcam is needed  

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Cooper-Hewitt#37]

**Comment by Carsonsmuts** [comment]
If everyone is happy with the location then yes, we can fix it permanently. How high off the ground is currently an acceptable distance? When I cut plates for table later this week, I was planning on cutting support plates for the camera.

**Comment by RELNO** [comment]
@Carsonsmuts thanks! as long as we get the scanning area, any above the ground setup will do
<img width="1031" alt="cam00001" src="https://user-images.githubusercontent.com/14296774/47721586-cfebb880-dc26-11e8-9feb-90aa41848a6a.png">

**Comment by agrignard** [comment]
Duplicate of #56
