### ISSUE TITLE
[Oct 29 meeting follow up] Building list should start from 0 for all 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Cooper-Hewitt#39]
This has been briefly mentioned [here](https://github.com/CityScope/CS_Cooper-Hewitt/issues/12#issuecomment-433751822), but it seams there is some confusion as to how we count the list of 24 building types. So, regardless of your [background](https://images.lookhuman.com/render/standard/4620052260860634/3600-athletic_gray-z1-t-trust-me-i-m-a-programmer.jpg), culture, religion or favorite coffee, let's please all agree that types list starts at ZERO. That is: **the first type/building/lego building is [0], the next [1] .... the last is [23]**

It might require a couple of edits at your end now, but will save us a lot of debugging later.

**Comment by aberke** [comment]
I imagine renumbering the blocks could be confusing for the design team since they had designs and uses assigned for each blocks.
Design team: what would be the least disruptive way to renumber the blocks for you?

Option a)
Renumber block 24 as block 0. Leave all the other blocks unchanged 

Option b)
Renumber each block as one number lower. I.e.
Block 1 —> block 0
Block 2 —> block 1
… and so on 

(Other options?)

**Comment by RELNO** [comment]
@aberke
 > Option a)
Renumber block 24 as block 0. Leave all the other blocks unchanged

is not really an option from the scanning side of things [and I guess for simulation team as well], as we organize our parsing based on a certain order. 
Let's try to converge on simple 0-23 [your B option]

**Comment by guadalupebabio** [comment]
Design team have already renumber the bocks. We are using from 0-23

**Comment by popabczhang** [comment]
I agree that we should unify the numbering to start from ZERO. That's also how all other CityScope tables were done. 
Yesterday, @guadalupebabio told me that the pieces in Rhino are numbered starting from ZERO. I guess they are doing for other media as well.

**Comment by aberke** [comment]
Great, I just made the following updates for this too:
- blocks data in the [spreadsheet](https://docs.google.com/spreadsheets/d/1aKRPp83EWWdBri6MwjuGcZVSki2xQuxd_OjMAdrrpS4/edit#gid=0) numbered 0-23
- blocks.csv and simPop.csv data updated accordingly (PR that did this: https://github.com/CityScope/CS_activityBased/pull/10)

**Comment by yasushisakai** [comment]
```
       _              _               
      | |            (_)              
  ___ | |  ___   ___  _  _ __    __ _ 
 / __|| | / _ \ / __|| || '_ \  / _` |
| (__ | || (_) |\__ \| || | | || (_| |
 \___||_| \___/ |___/|_||_| |_| \__, |
                                 __/ |
                                |___/ 
 _                                    
(_)                                   
 _  ___  ___  _   _   ___             
| |/ __|/ __|| | | | / _ \            
| |\__ \\__ \| |_| ||  __/            
|_||___/|___/ \__,_| \___|            
                                      
                                      
```
