### ISSUE TITLE
PEV+CityScope Shared space (Cooper Hewitt Requests)

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#4]
**CH** - "I still can’t yet confirm whether the PEV and CityScope will be displayed adjacent to one another, but I think it’s most likely that they won’t be."

**CS** - This is a pity. Both pieces are somehow linked, however, we will adapt to the curator decision. Please, let us now the final decision as soon as possible.

Issue: To be ready for the two options (Follow up to see the final decision)

**Comment by agrignard** [comment]
Regarding the last discussion I have had in CH they will be on the same floor
