### ISSUE TITLE
Scanner submodule [git hook or remove] 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Cooper-Hewitt#40]
As discussed, Scanner s/m is confusing for someone who pulls recursively, as it is not local nor the s/m is being updated frequently enough.  
Please set it as as git hook to point HEAD, or remove s/m and add link to readme that points to latest commit.

**Comment by yasushisakai** [comment]
just a heads up!
@agrignard @aberke @Carsonsmuts @popabczhang

due to our(@RELNO) decision, we detached the scanner repo. 
pulling this repo should do it's job, but if you see the **Scanner** folder
as if it is ready to be commited/pushed, it is safe to go ahead and remove it (```rm -rf Scanner```)

... And I won't be mad if you accidentally push it.

**Comment by yasushisakai** [comment]
for @RELNO 

what I found new is there is no git hooks for post-push, reason coming from a  **philosophical** standpoint from the git maintainers.

the right way seems to write a git alias in ```.git/config```. which you might be interested if you are divining into git by command line. so much fun.
(obviously it was easier to remove it for this situation)

**Comment by RELNO** [comment]
@yasushisakai tnx, 'terminal git' sounds like a serious health related issue. 

@agrignard @aberke @Carsonsmuts @popabczhang - for context: Scanner can be updated 4 times an hour when we calibrate, so having s/m commit for each of these would make no sense.
Instead, clone HEAD from the link in the readme https://github.com/CityScope/CS_Cooper-Hewitt/blob/master/README to be on the safe side

**Comment by RELNO** [comment]
@yasushisakai github is so much fun this time of the year 
<img width="711" alt="screen shot 2018-10-31 at 11 34 17" src="https://user-images.githubusercontent.com/14296774/47799621-085fc500-dd01-11e8-88e4-946a5c902377.png">

**Comment by agrignard** [comment]
"Scanner can be updated 4 times an hour when we calibrate"  

it doesn't mean you have to push 4 times/hour in the repo? 

Why d'ont you push just once it's calibrated ?

**Comment by RELNO** [comment]
Ideally yes, in reality (now) whenever someone interacts with table internals the cam moves. You can argue we shouldn't push the calibration file, but that would force someone to recalibrate whenever there is a change

**Comment by agrignard** [comment]
Yes I get the point that each physical move is a new keystone and potentially a new push.  This is the same each time a mirror move in the simulation a new keystone is produced and pushed (or not but ideally yes) here:
https://github.com/CityScope/CS_Cooper-Hewitt/blob/master/ABMobility/keystone.xml

It doesn't happen that often and let's hope it will happen less and less. 

Anyway it is just a pointer to one another repo, not convenient and getting further than the one click/one repo/one project  option but if it has to be like that it is how it is

**Comment by RELNO** [comment]
> Anyway it is just a pointer to one another repo, not convenient and getting further than the one click/one repo/one project option but if it has to be like that it is how it is

Close to deployment and handover to CH ppl, the plan is to reintroduce the scanner submodule into the main repo [and allow one click clone etc]. But for now, since the scanner is talking to multiple endpoints, it's important we all share the same latest version.

**Comment by agrignard** [comment]
ok
