### ISSUE TITLE
NPE in ABM.pde line 290

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#45]
current master d2ccf797da8d6746e44e896c3bb3180159b0defc 
throws Null Pointer Exception in line 290

this was observed after 10-20 min after running.

```
ArrayList<Node> newPath = map.graph.aStar(srcNode, destNode);
```

@agrignard is this what you saw in #32?

**Comment by agrignard** [comment]
ouch... bad news... I guess it's the same one. hard to reproduce the table is running for a while now. So I guess a very specific node in one of the graph is producing this bad bath....

**Comment by yasushisakai** [comment]
updated, now it is line 305 in 7b38144e851d0a2d5db4f7edc73caaba6cfc7bfc

I do not see anyone touching the ```map.graph.aStar(srcNode, destNode);``` portion, 
we still see this.

@aberke do you see something related?

**Comment by cpgmedialab** [comment]
for documentation, the mac pro had the same NPE error running  89c4969
Y.S.

**Comment by agrignard** [comment]
Hi @cpgmedialab who are you ;-) ?

So regarding this issue. I just push a version here https://github.com/CityScope/CS_Cooper-Hewitt/commit/0930e02cf0070b3f6232d13312c4be9e3076be2f that at least runs for ever.

So what I did I rename the suspect graph bike_2_issue45.geojson (so we can work on cleaning it) and then I replace bike_2.geojson by bike_1.geojson. 

It means that right now the bike network of the good world is the one of the bad world but at least we have a demo runnign forever which is more important.

So I will run this version on the table so we can  verify that this is running without any problem

**Comment by yasushisakai** [comment]
closing since we don't have this behavior 0930e02

**Comment by agrignard** [comment]
With the new multi threading, I reput the complex bike_2.geojson so let's stresstest it. I run the simu yesterday night in the lab let's see how long it runs. I am also running it on my laptop. 

So far so good but we know it can take a while. let's close this issue if we can run the simu for more than 24 hours

**Comment by agrignard** [comment]
Let's see if this happens again but I fell pretty confident. let's close this and hope not to reopen it
