### ISSUE TITLE
One way graph direction

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#46]
Now that the graph are almost done (almost see #45 and #32 ) we have to realive the one way feature so that car doesn't cross each other on the same road.

@yasushisakai I kind of lost the track of what we did here

The very original model (at least the Andorra One) is taking in account the direction of the road but I don't remember when we decided to remove the isAdjacent concept.

**Comment by yasushisakai** [comment]
Looking into the network, I feel (without full confidence) we don't have a dead end node.
Plus, the origin and destination Node will be a small portion of the whole.

```isAdjacent``` was originally to address this, but I think we can (and should) live without it.

Note that the property ```oneway```(which was originally used for Andorra)  is optional, if the rhinoceros file is drawn in the **right** (@LAAP ) way, the order of the coordinates will be directional, and we can decide which network should be bi or mono directional.

**Comment by LAAP** [comment]
Hi, there is the latest graph available

It is a 1 direction graph "car_1_1direction". It works locally in Processing, **but the agents are not following the 1 direction** (They are still choosing the direction randomly)

We may need some coding-magic behind the graph

@agrignard @yasushisakai @aberke , please, let me know your thoughts

"Suerte y al toro"

**Comment by agrignard** [comment]
@LAAP the file is empty

also i'd like to keep only the really working graph. I cleaned the network folder with the folder called current_network for the one that are running and that has been tested on the table and then we have a testing folder to experiment with new graph . So for instance car_1_1direction will go in this folder

**Comment by LAAP** [comment]
Done and pushed.
I think that the graph is working: However, Agents gets randomly in a road, and then they stick with the direction. It doesn’t mean that they behave properly following traffic conventions

**Comment by agrignard** [comment]
I don't get how this issue was close without pushing new graph in the repo? 

@LAAP did you push some new graph with the oneway feature?

**Comment by LAAP** [comment]
@agrignard , I have pushed a new graph car_1 has been replaced. Please check it

**Comment by LAAP** [comment]
Maybe I forgot to sync

**Comment by agrignard** [comment]
Yep now it's here with this commit
https://github.com/CityScope/CS_Cooper-Hewitt/commit/c5a10593f6d53c4420ea2615500b8a8966d90cf0

So did you update the graph that is really used? I mean in the folder "currentNetwork"? In the crurrent one I see that oneway is always false

https://raw.githubusercontent.com/CityScope/CS_Cooper-Hewitt/c5a10593f6d53c4420ea2615500b8a8966d90cf0/ABMobility/data/network/current_network/car_1.geojson

**Comment by LAAP** [comment]
Hi Arnaud. Yes. I have moved the old car_1 to the folder old, and I replace it for the new car_1 at the folder "currentNetwork" folder

**Comment by agrignard** [comment]
I reopen this issue as it seems that it is not working (but close to work)

**Comment by LAAP** [comment]
It is ready and working. I will push as soon as you give me the "go-go"!

**Comment by yasushisakai** [comment]
Closing since @LAAP, made the good network on #95
