### ISSUE TITLE
initAgentInsideBuilding() shifted??

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#47]
I remember @agrignard talking about this, but 
while me doing NetworkEdge class #21 I saw an error (IOB) that it couldn't find
any nodes in that box search area.

![spawn_frame_1](https://user-images.githubusercontent.com/1502180/47841537-4bb54480-dd90-11e8-9c81-68d91452d9fd.PNG)

Above is the first frame of it, It looks like it is trying to spawn from the middle of the road

is this still the case?? 
if not, please go ahead and close this, wanted to know the status.

**Comment by LAAP** [comment]
Not sure to understand the issue

**Comment by agrignard** [comment]
I don't get it either

**Comment by yasushisakai** [comment]
closing since we cant validate this. we may revisit this when #45 #48 seems fine.
