### ISSUE TITLE
IOB error in ABM.pde same line as #45 (305)

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#48]
7b38144e851d0a2d5db4f7edc73caaba6cfc7bfc
throws an IndexOutOfBounds Error in the same line as #45 

PR https://github.com/CityScope/CS_Cooper-Hewitt/pull/44 was working in isolation
(8h+, mac book pro), hence the merge. (I don't think it is related to networks or shortest path finding)

@agrignard, @LAAP  Is this because of the network? #32 

**reverting is doable via PR**

**Comment by yasushisakai** [comment]
update: using

```simple_and_complex_network```
```simpler_network```

throws a different error in RoadNetwork.pde line 137
```
public Node getRandomNodeInsideROI(PVector pos, int size){
...   
    return tmp.get(int(random(tmp.size())));
}
```

@LAAP?

update2: checking out few commits before throws the same errors, I suspect it is the network.

**Comment by LAAP** [comment]
Maybe? Is there any way to test the nodes and the vectors that are working in the network?
As far as I know, all the nodes and vectors are connected properly, but we may have a "graph-dead-short".

**Comment by yasushisakai** [comment]
46cee3d6fd2953934039e431957e0b7a3c8a5e05 
has a network checker processing sketch now.

**Comment by agrignard** [comment]
let's hope that the recent modif about multi threading will solve it. I am running the last version of the master in the lab right now. Let's see how long it will run

**Comment by yasushisakai** [comment]
It's stable on my side too

**Comment by agrignard** [comment]
did you run the last master? no crash?

If it's ok until tomorrow we can then close this issue and #45

**Comment by yasushisakai** [comment]
@agrignard agreed

> did you run the last master? no crash?

currently I'm running this in two computers, the test table and one computer at home.

**Comment by agrignard** [comment]
Let's see if this happens again but I fell pretty confident. let's close this and hope not to reopen it
