### ISSUE TITLE
Table Design and ADA guidelines (Cooper Hewitt Requests)

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#5]
**CH** - "Are you at all interested in placing the CityScope model on our exhibition furniture?"

**CS** - Thank you for offering, but we will need to use our own design

**CH** - "If you were to build the table, it would be very helpful to share any shop drawings of the piece and minimally to know the height and weight as soon as possible as this affects our shipping contract. The table would need to conform to ADA guidelines to be wheelchair accessible—I can share our requirements with you next week."

**CS** - Totally; we will try to share as much material as possible. Please, share with us the ADA guidelines, so we can keep that on mind during our design process. Thank you in advance!

Issue: we need to meet ADA guidelines.

**Comment by yasushisakai** [comment]
work around assuming side access for wheel chairs

![backoff](https://user-images.githubusercontent.com/1502180/45906815-8a380680-bdc3-11e8-9c3d-9dc291e1e947.PNG)

**Comment by yasushisakai** [comment]
![backoff](https://user-images.githubusercontent.com/1502180/45909211-95446400-bdce-11e8-823e-9db3299bcc45.png)

**Comment by yasushisakai** [comment]
- ADA guidelines pp34
![wheel_chair_side_access](https://user-images.githubusercontent.com/1502180/45909305-10a61580-bdcf-11e8-8a9e-61d0f1983c44.PNG)

**Comment by yasushisakai** [comment]
- finishing examples (closer to PEV)
  - metal coating (baking finish)
    - melamine?
    - acrylic?
  - Fiber Reinforced Plastic?
  - paint?

**Comment by LAAP** [comment]
Thank you @yasushisakai , I think that

**Comment by LAAP** [comment]
I think that this is great. The challenge is that for any of the 3 options, we will need to find an external contractor to do the job before Thanksgiving.

**Comment by yasushisakai** [comment]
My understanding is that @Carsonsmuts is taking care of this.
Thank you @Carsonsmuts !

closing
