### ISSUE TITLE
zombie land exists

### ISSUE THREAD

**Issue by aberke** [CityScope/CS_Cooper-Hewitt#51]
We need two new functions:

1. function to check if a given building is on table or in zombie land
2. function to get random node from zombie land

Either Alex or Arnaud will do this.

**Comment by agrignard** [comment]
1. function to check if a given building is on table or in zombie land
see https://github.com/CityScope/CS_Cooper-Hewitt/commit/0aa80db08b8c0c7916f02475d68688cd44d4c2a4

2.function to get random node from zombie land
see https://github.com/CityScope/CS_Cooper-Hewitt/commit/65cbf1fffd182e519a56b5ff6ef74bd55eb00765

Issue almost closed however how we need to test it on the table (which is not really possible in the current "state" of the physic table)

**Comment by agrignard** [comment]
Potentially done in 65f5020

Need to test it on the table  (see #55 ) (with only one building for instance) Right now only agent having a rID of oID greater than 18 are coming or going to zombie land

**Comment by aberke** [comment]
Nice!
