### ISSUE TITLE
Hardware Issue Tracker 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#56]
Here is the list of all the "issue" related to the hardware mainly mirror, scanning and projector (nothing to do with code so they are regrouped in one issue)

- First surface Mirror sizes https://github.com/CityScope/CS_Cooper-Hewitt/issues/11
- bottom projector and mirror location https://github.com/CityScope/CS_Cooper-Hewitt/issues/22
- permanent fixing of webcam is needed https://github.com/CityScope/CS_Cooper-Hewitt/issues/37
-  all 3 projectors don't work together on new Mac Pro https://github.com/CityScope/CS_Cooper-Hewitt/issues/38

**Comment by yasushisakai** [comment]
@agrignard  thanks for making things clear

**Comment by popabczhang** [comment]
👍
I will add two: 
WiFi 4K display stability with Unity 3D projection mapping;
If 4K projection could cover the whole table.

**Comment by agrignard** [comment]
First surface Mirror sizes #11 => ordered
bottom projector and mirror location #22 => done
permanent fixing of webcam is needed #37 => done
all 3 projectors don't work together on new Mac Pro #38 => tested and it's working

so happy to close this issue

**Comment by RELNO** [comment]
Test or final plexi surface cut with holes for buildings needed for testing

**Comment by agrignard** [comment]
I close this one which is implying to many mixed isssues
