### ISSUE TITLE
Dynamic rerouting of Agent according to the building position

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#57]
The init of Agent according to the building id and initial condition has been done in #42 we need now to implement a dynamic rerouting of the agent ones the user moves a building.

On an iteration based style we could think about this:

1. One of the first version will be a brutal reInit each time a building is moved. It might be enough in most of the case. It however required a very stable scanning that send changes only if a building has been moved other wise we will have an init any time a value changed

2. Each time a building has been moved we could check the agent concerned by this moving (the one that lives and/or works in this building) and ask them to reroute them self

However mainly due to #56 it is now impossible to test it.

**Comment by agrignard** [comment]
I just had a way to display the zombie in red in https://github.com/CityScope/CS_Cooper-Hewitt/commit/8ce9dad6ddf9ea6071976d21a9a0d482f0e92362 it is commented for now but by decommenting it , it will help to fix this issue by identifying the zombie in red

**Comment by agrignard** [comment]
FYI GetRandomNode from Zombie Land is finally doing it's job https://github.com/CityScope/CS_Cooper-Hewitt/commit/35f832d7f60e7acd59b6f34aa7fa4cb446ede652 (it was not the case before) most of the zombie node where in x<0 and y<0 (because of the scale factor) so they were all coming from the top or the left but never from the buttom and the right (that might explain the vomiting building behavior (many zombie were going though this one)

**Comment by agrignard** [comment]
This is one of the important feature that a user want to see on this table. What happens when I move a pieces.

Does anyone has the chance to test with the table to see what is the current behavior?

Ideally the rerouting should happen how ever it might just take time and we might have also to amplify the repartition between R and O to really see the impact.

It's important to test it asap on the table so we can understand what to change.

@aberke, @LAAP , @yasushisakai  can you have a look at this one?

**Comment by aberke** [comment]
Hi Arnaud, 
Luis and Yasushi were unable to test interaction on the table yesterday because of hardware work being done.  We have scheduled time to try again today (4-5pm).  Fingers crossed all hardware work will be complete by then so that we can have a successful test and meeting.

**Comment by agrignard** [comment]
This is strongly linked to #84 I close this one for more clarity
