### ISSUE TITLE
Increase the number of Agent

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#59]
There is a problem in the current version it seems impossible to increase the number of Agent.

Right now it set to 800 in createAgents(800); however we shoudl be able to play with the numebr of agent easily. Right now it produces a weird error in CalcRoute()

ArrayList<Node> newPath = map.graph.aStar(srcNode, destNode);

Step to reproduce:

````
createAgents(1000);
````

**Comment by aberke** [comment]
Fixed by https://github.com/CityScope/CS_Cooper-Hewitt/pull/60
