### ISSUE TITLE
LEGO security (Cooper Hewitt Requests)

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#6]
**CH** - "how the Legos can be secured to the table so that people can still move the relevant pieces."

**CS** - We are thinking of having big (something like 35x10x20) LEGO buildings, with glued pieces, so stealing the whole building will be difficult. We can also have some extra buildings to replace the damaged ones.

Issue: We need to think a bit about this

**Comment by agrignard** [comment]
Lego are being glued
