### ISSUE TITLE
Visualizing Congestion 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Cooper-Hewitt#61]
A quick sketch following the discussion today. Basically emitting some grad flickering light on roads close to congested buildings:
![ezgif-5-2ba643f6e2a2](https://user-images.githubusercontent.com/14296774/48158954-ef778680-e2a1-11e8-9bc5-789958260f03.gif)

![ch_streets_bad_red_01-05-05](https://user-images.githubusercontent.com/14296774/48159004-1a61da80-e2a2-11e8-835d-96a9bb5bf947.png)

**Comment by guadalupebabio** [comment]
What about if same wife effect appears when special pieces are display? it would be projected from above
![maxresdefault](https://user-images.githubusercontent.com/38555658/48164785-8730a100-e2b1-11e8-9297-27a705b215c1.jpg)

**Comment by aberke** [comment]
Ideas for technical implementation from meeting:

1. Count number of cars in world, and make speed for cars slower when there are more cars
2. Weight the graph depending on how many agents are on it
E.g. car graph has more agents on it, it has higher weight → agents more more slowly

**Comment by yasushisakai** [comment]
I want to revisit this topic, implementing this in the simulation side.  #99 has more priority (@LAAP, right?), this was also requested in the followup meeting too.

0. Cars stopping to avoid collision (***)
1. Alex's comment above
  - change speed according to the number of agents sharing the path. (**)
2. Show paths that are congested. (**) 
3. Overlay fill color (alpha varies) (similar to @RELNO's image) or in other words heatmap of agent (**)
4. Simple coloring of intersections

comments open till friday morning.

@RELNO, @LAAP, @agrignard 
@yasushisakai will implement this through a PR. (Thus will be kicked if I mess up.)

**Comment by LAAP** [comment]
Right, @yasushisakai . I see that the team is pushing to get the A+++. I am impressed. Good job, everyone!

**Comment by agrignard** [comment]
Late comment as I was focusing more on #99. 

1. Having the car slowing down would be a plus only and only if if it doesn't decrease the framerate/computaion however I am afraid that it will be greedy to compute but it is worht trying if someone is interesting to implement it

2. For the congestion my feeling is that the table should speak  by itself. With a good design we don't need heatmap to abstract what we have.  Also the table is already pretty in an 80's baroque style, if we had an heatmap to show the congestion it might be too much (almost anachronic in term of design)  mixing 80's rendering and 90-00's with an heatmap.

3. Not to mention that we are in the last mile so an modification should be done very carefully now.

**Comment by agrignard** [comment]
We could imagine a special mode where we see the congestion in the bad world and the collision potential in the good world

The question is how to we trigger this, or do we keep this as a default rendering.

Need to be discussed in term of design style
<img width="1658" alt="screen shot 2018-11-26 at 11 42 02" src="https://user-images.githubusercontent.com/3928502/49028460-74064800-f170-11e8-8243-2e5442f85072.png">

**Comment by agrignard** [comment]
Work in progress
https://github.com/CityScope/CS_Cooper-Hewitt/pull/105

**Comment by agrignard** [comment]
solved
