### ISSUE TITLE
Running the table problems

### ISSUE THREAD

**Issue by cpgmedialab** [CityScope/CS_Cooper-Hewitt#62]
Several problems have found so far when trying to set up the table:
-Python Scanner not running
![img_7036](https://user-images.githubusercontent.com/29551714/48286728-8ecc8300-e434-11e8-8248-1fb8bb83fd2a.JPG)
-When the projectors are running and the screens are not mirror is a mess, the apple screen should be set by default.

I can write the initialization process for the table as it will be run by a estranger and everything should be clear and easy.

**Comment by RELNO** [comment]
@cpgmedialab who are you? :)

**Comment by RELNO** [comment]
Power jump killed USB ports and projectors, as well as the camera USB port. We'll reconnect the whole system now.
