### ISSUE TITLE
Final Integration Tracking in GitHub Consolidation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#64]
We know for many different reasons that it's difficult to have all the code in the same repo. However with the deadline arriving I think it's getting critical to consolidate the github not only on the code but on the documentation also). Right now it's getting very hard (not to say impossible) to track the evolution of the project. 

This is the current activity that one can see of the github now appart ABMobility nothing has been updated since more that 2 weeks (which is not true but this is what we see) so it makes impossible to know who is working on what

<img width="989" alt="screen shot 2018-11-13 at 13 18 14" src="https://user-images.githubusercontent.com/3928502/48413003-964a9f80-e746-11e8-8220-9a393156ea58.png">

The best solution would be to have everyone trying to push in this repo at least to update the submodules (when they exists) so we know something has changed.

@yasushisakai what do you think? What about forcing the update of the submodules?

**Comment by yasushisakai** [comment]
@agrignard should we delete irrelevant submodules? (e.g. graphic studies)

People (@popabczhang @RELNO) can ping me or @aberke  if they need help updating the submodule.

**Comment by agrignard** [comment]
If they are not really used yes I think we can delete them

**Comment by yasushisakai** [comment]
related #67 
Should we have a convention for this project where to have documentation?
wiki? README?

**Comment by agrignard** [comment]
I think The wiki is the place with a bit of reorganization. especially if we want to put picture we don't want to put image in the repo so the README should be for minimal information. Like the root README could have some basics information about the project and then point to the wiki for more specific details.

**Comment by yasushisakai** [comment]
This issue will kept alive, until the deployment && documentation on wiki is complete.

**Comment by agrignard** [comment]
merge in #75
