### ISSUE TITLE
RGB Color for the project

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#65]
Would it be possible to have the RGB value used in this project? (ideally in the  wiki) 

I'd like to update the color of the Simulation which is now pure Red,Green and Blue.

Can we agree on the color to show people walking, biking, driving and pev

Currently we have 

car: rgb(255,0,0)
bike: rgb( 0,255,0)
ped: rgb(0,0,255)

**Comment by gabrielabila** [comment]
The people, cars and bikes are supposed to be white (255,255,255). The difference is about the shape of each of this elements (we have a little icon for car, bikes...).

**Comment by agrignard** [comment]
We also have other mode (we still need to discuss if we want to show it or not and how to trigger it but it s another question) where we display the mode with color, also when showing the graph so we ll need the same rgb value

**Comment by gabrielabila** [comment]
Ok, so using this color mode, would be possible to have them different in good/bad? 
If YES, here are the colors:

BAD
car: rgb(255,255,255)
bike: rgb(120,52,165)
ped: rgb(255,85,118)
GOOD:
car: rgb(255,255,255)
bike: rgb( 0,234,169)
ped: rgb(141,198,255)

If it's NOT possible to change color in each world, here are the colors:
GOOD AND BAD
car: rgb(255,255,255)
bike: rgb(120,52,165)
ped: rgb(255,227,26)

**Comment by agrignard** [comment]
I am a bit surprised by those color, this is how it looks, maybe it match with unity  but I am bit surprised. i will try to implement a different color for each world soon also

<img width="1134" alt="screen shot 2018-11-13 at 21 48 03" src="https://user-images.githubusercontent.com/3928502/48442206-d41ee680-e78d-11e8-8217-bad95798fbf1.png">

car: rgb(255,255,255) => white?
bike: rgb(120,52,165) => purple ?
ped: rgb(255,227,26) => yellow?

**Comment by agrignard** [comment]
Ok so here is how it looks (press g to trigger the color mode). It will be iportant to see how it looks on the real table with unity displayed also. 

I am not sure we should display the car in white but now it's quiet easy to change those color. So Agent and roadnetwork are now using the good and bad value



<img width="1146" alt="screen shot 2018-11-13 at 22 03 49" src="https://user-images.githubusercontent.com/3928502/48443190-9a9baa80-e790-11e8-95bb-dc5bc155ba88.png">
