### ISSUE TITLE
Network graphs do not go through buildings.  

### ISSUE THREAD

**Issue by aberke** [CityScope/CS_Cooper-Hewitt#66]
Luis will update the graphs so that roads do not go through buildings.  

Goal: agents do not travel through buildings

**Comment by LAAP** [comment]
A totally New set of graphs avoiding building shortcuts

I made all the graphs again cutting the short path through buildings. This also gives more nodes inside of the building and a better distribution of the nodes in the "doors" of the building

**Comment by agrignard** [comment]
Nice!!! So I guess you have the rhino graph with the oneway feature, i see in the commit that the feature is not here but maybe you can retry with the last version of GAMA and the last model pushed (see issue #73 )

**Comment by LAAP** [comment]
@agrignard , I don't have a good one direction graph yet, but I will try to have it before the 16th

**Comment by agrignard** [comment]
ok i though there was a problem with the one way according to this
https://github.com/CityScope/CS_Cooper-Hewitt/issues/73
