### ISSUE TITLE
documentation for how the graphs are created and how they connect within buildings.

### ISSUE THREAD

**Issue by aberke** [CityScope/CS_Cooper-Hewitt#67]
Luis will document how the graphs are created and how they connect within buildings.

**Comment by yasushisakai** [comment]
where should we write this? #64

**Comment by aberke** [comment]
Documentation should either be in
a) wiki
b) README in folder: CS_Cooper-Hewitt/ABMobility/data/network/current_network/

**Comment by LAAP** [comment]
I will do this in the future with images. However, there are 2 or 3 rules that are basic like: 
-no to overlap lines
-the graph (circuit) needs to be closed
-you can not have "short circuit"

**Comment by agrignard** [comment]
The issue has been refered in the wiki of the graph (I close it but the issue stays accessible)
