### ISSUE TITLE
GAMA cleaner removing the "oneway" properties spit from rhinopython

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#73]
## Now
after the cleansing via the  GAMA process, we no longer see the "oneway" property in the geojson.

## Should
preserve the property so that, when used in processing, it should interpreted as an one way network.

@agrignard I added you, since I didn't know who should I assign,
-> should I add him/her as a contributer?

**Comment by agrignard** [comment]
The last version of gama and is corresponding model.gaml is keeping this attribute.

I think we can double check this with @LAAP

**Comment by yasushisakai** [comment]
thanks will do w/ @LAAP

**Comment by LAAP** [comment]
Hi, not sure. @yasushisakai have been looking on it this morning and seems that the attributes are not there anymore.

**Comment by agrignard** [comment]
Ok the model in the github was not the last version sorry. 

I have updated the model in the model here
https://github.com/CityScope/CS_Cooper-Hewitt/blob/master/CH_GAMA/models/Graph_Cleaner.gaml

I tested on my machine it works

Remember that this feature has been added recently in GAMA so you need to run this model with the continous build that you can find here , then run the model and it will produces a road_clean.json

https://gama-platform.github.io/download#

Let me know if it works

**Comment by yasushisakai** [comment]
@LAAP was performing a stress test on one of the computers, but as far as I saw it behaved well. For the observation of them actually taking mono directional, excuse me for the ambivalent comment but we **felt** it was working.
