### ISSUE TITLE
JSONArray[0] is not a JSONArray.

### ISSUE THREAD

**Issue by cpgmedialab** [CityScope/CS_Cooper-Hewitt#74]
Simulation was found dead with the error of this issues subject
Grid.pde line 45 

Y.S.

**Comment by agrignard** [comment]
Was it from the last master? line 45 is          b.draw(p); so it's weird.

It might be related to the update of the grid and the Json receive by the scanner

CAn you dig a bit more? is it happening at the initialization or after a while?

**Comment by agrignard** [comment]
I cannot reproduce this bug on my machine.

**Comment by yasushisakai** [comment]
I suspect this is a parsing error between the scanner. Will be watching for this.

**Comment by agrignard** [comment]
I close this one, Felle free to reopen if it rehappens

**Comment by agrignard** [comment]
I close this one, fell free to reopen if it rehappens
