### ISSUE TITLE
Background image tiny offset

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#76]
@gabrielabila good job for the background it looks cool.

I have integrated it in the code so you can see how it looks on the table 

However it seems that there is a slightly offset, at least on the rendering if you see the building in the middle the sidewalks are a little bit offset. I don't know exaclty where it comes from maybe we won't see it on the table but I just wanted to notice it.

<img width="1063" alt="screen shot 2018-11-14 at 11 33 16" src="https://user-images.githubusercontent.com/3928502/48477351-a7a4b200-e801-11e8-9a94-d17fc33f0768.png">

**Comment by agrignard** [comment]
@gabrielabila and/or @guadalupebabio any update on this?

**Comment by agrignard** [comment]
@gabrielabila can you have a look at this one? It's a detail but still

**Comment by gabrielabila** [comment]
@agrignard, I can't detect this offset in my files here. When we had the illustrations on the table this topic was never raised.

**Comment by agrignard** [comment]
ok nobody noticed so nobody will ever notice. let's put it in the too touchy issue
