### ISSUE TITLE
Mac Pro Failed to Install Updates

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Cooper-Hewitt#77]
This is how we found the Mac today.
While we can try debugging this, at this point the simplest thing is reinstalling all from scratch to ensure error free OS. 

![img_20181114_094605](https://user-images.githubusercontent.com/14296774/48490145-c2bbf580-e7f2-11e8-97f1-370066a95b04.jpg)

**Comment by yasushisakai** [comment]
we will monitor this and if we see this same problem
once more within 16 hours (Thursday noon) we will perform a factory reset level install.

**Comment by agrignard** [comment]
This is strange. In any case I think we don't want this computer to update by itself, if we can ask from the OS to shutdown the automatic update and also turn off the wifi once in CH we can avoid this kind of behavior.

However I am not sure we can turn off the automatic updates on the latest Mac OS...

**Comment by popabczhang** [comment]
@Carsonsmuts  restarted the MacPro and it's magically recovered. Then he updated the security update with no issue. Then he disabled the automatic checking for update function completely. 

Notes: now Mac OS does automatically download and install security updates (only security updates). that caused this issue.

**Comment by Carsonsmuts** [comment]
@agrignard @RELNO @popabczhang @yasushisakai Look, the error last time apparently mentioned OpenGL. So I am not at all surprised. One simply cannot have a computer running the kind of things we are running and then let the OS install updates to anything GPU or driver related. If we do, this will just happen again and again regardless of clean OS. Rule of thumb, if it happens once, it will happen again, unless you remove the cause. If we cannot find the cause , all we can do is disable the updates.... this is on top of installing a new OS of course... if people have not done so already.

**Comment by agrignard** [comment]
I think we just have to turn off the update form this computer. We clearly don't want to have a new version that might affect the current behavior.

So the idea is to turn off systematically the automatic update on this mac, which is by default not that easy anymore on our beloved mac OS...

Maybe one start can be this:

https://appletoolbox.com/2018/01/disable-macos-software-update-upgrade-notifications/

**Comment by agrignard** [comment]
For instance maybe only doing this is enough

You can use the Terminal Command **sudo mv /Library/Bundles/OSXNotification.bundle ~/Documents/** and then enter your admin password to confirm. Then restart your Mac. This Command surpresses all macOS Notifications moving forward

**Comment by yasushisakai** [comment]
If we aren’t putting a SIM card into it, it won’t be able to update at the venue.

**Comment by agrignard** [comment]
Yes if there is no internet it won't update of course, I am more worry about the automatic popup that appears on the top right of the screen, if we can try to be sure that this won't pop up from nowhere, that woudl be great. But maybe just not being connected to internet is ok

**Comment by Carsonsmuts** [comment]
I am reinstalling the system right now. I will disable updates, again, this time at a lower level....  and I will most likely block all ports to apple update just in case once everyone is happy with the system. 

FYI. If anyone was running an overnight test, everything was still running as of 6:00am when I got here.

**Comment by yasushisakai** [comment]
Please open this when needed.
