### ISSUE TITLE
Agents use motifs with amenities

### ISSUE THREAD

**Issue by aberke** [CityScope/CS_Cooper-Hewitt#78]
## Currently: 
All agents have motif ROR: they go Residential --> Office --> Residential (again and again)

## Next steps

1. All agents use motif: ROAR (with amenity hardcoded from data)

2. Agents dynamically choose their amenity

3. (reach goal) Agents use motifs from data

**Comment by aberke** [comment]
This implements (1) + (3): https://github.com/CityScope/CS_Cooper-Hewitt/commit/9e657b25d25729953a908b2160d02249dc363b8a

A next step would be to have the agents dynamically choose their amenity blocks (if we want that).
That changes is dependent on PR https://github.com/CityScope/CS_Cooper-Hewitt/pull/79

**Comment by aberke** [comment]
(oops I forget to CC)
FYI @LAAP @yasushisakai @agrignard

**Comment by agrignard** [comment]
This is a good idea however what about focusing first on amplifying the ROR commut so we can really see pattern happening? I am afraid that introducing the Amenties will produce maybe something more close to the "reality" but it will be hard for the user to see the impact of moving one building quickly but let's see

However it's good do start this task in parrallell as soon as it's easy to run the ROR pattern

**Comment by yasushisakai** [comment]
Closing since I see this running smoothly, and still there in @ b43290

Yet @agrignard ’s claim is right. To both have the reality and to show what is happening, I think we want to #99 for our answer of this iteration.
