### ISSUE TITLE
Bike and Car Network 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#8]
@yasushisakai It seems that there is sometime some error on the bike and car network that doesn't appear on the ped network.

Maybe we could think about using a QGIS software or something else to validate that the graph is fully connected.

**Comment by yasushisakai** [comment]
let me clarify the error.
```
toNode = path.get(path.size() - 2);
```
producing an AIOB error.
is this positive?

**Comment by yasushisakai** [comment]
cleaned the .geojson file
