### ISSUE TITLE
Slider crash when unity gets into scene

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#81]
Dear @yasushisakai  @Carsonsmuts  @RELNO @popabczhang ,

 I have tried to run everything at the same time.

Scanning, slider, and processing work very well together.
As soon as unity gets into the scene, everything slows down dramatically, and (maybe by chance) the slider crashed.

PS: I had tried to fix the slider, however, I also have crashed the scanner, but that is a side effect...

**Comment by popabczhang** [comment]
Not sure about if it is actually Unity. When I left today it 200 + fps with the slider and scanner. Let's check together tomorrow.

**Comment by popabczhang** [comment]
One suggestion, can we try to run everything together when everyone is together?

**Comment by popabczhang** [comment]
There might be a conflict in terms of UDP socket. Unity and Processing are both listening to Port 5005. It shall be better if scanner sents to two ports, for unity and processing separately.

**Comment by RELNO** [comment]
> It shall be better if scanner sents to two ports, for unity and processing separately.

Not sure where you get it, [there](https://stackoverflow.com/questions/1694144/can-two-applications-listen-to-the-same-port/25033226) [are countless](https://www.google.com/search?rlz=1C5CHFA_enUS778US778&biw=1440&bih=736&ei=zuLsW533H6nc5gLe1orQCg&q=+same+port+UDP+site%3Astackoverflow.com&oq=+same+port+UDP+site%3Astackoverflow.com&gs_l=psy-ab.3...4803.4803..5090...0.0..0.54.54.1......0....1..gws-wiz.......0i71.WrwjSpViEzg) SO results that argue differently

**Comment by RELNO** [comment]
merged into https://github.com/CityScope/CS_Cooper-Hewitt/issues/83

**Comment by popabczhang** [comment]
> > It shall be better if scanner sents to two ports, for unity and processing separately.
> 
> Not sure where you get it, [there](https://stackoverflow.com/questions/1694144/can-two-applications-listen-to-the-same-port/25033226) [are countless](https://www.google.com/search?rlz=1C5CHFA_enUS778US778&biw=1440&bih=736&ei=zuLsW533H6nc5gLe1orQCg&q=+same+port+UDP+site%3Astackoverflow.com&oq=+same+port+UDP+site%3Astackoverflow.com&gs_l=psy-ab.3...4803.4803..5090...0.0..0.54.54.1......0....1..gws-wiz.......0i71.WrwjSpViEzg) SO results that argue differently

good to know @RELNO .
