### ISSUE TITLE
Simetrical pieces work. Asymmetrical doesn't

### ISSUE THREAD

**Issue by guadalupebabio** [CityScope/CS_Cooper-Hewitt#89]
Hypothesis: did the camera flipped?
There are some pieces not being read but they used to. Can it be because of the flipped image? I think they used to work.
is it easy to flip it back?

**Comment by yasushisakai** [comment]
I second this issue, the labeling of the UDP stream seems to be flipped relative to the y axis (horizontal flip), the origin block (after confirmation with @guadalupebabio) was in the middle of the array not the first one.

@aberke, just a heads up that this relates to what we where doing, yesterday (Although I observed that still the agent behavior needs debugging)

**Comment by RELNO** [comment]
Have you tried flipping the scanning? If this is only a y axis flip, that's a low hanging fruit (😏) which only involves scanning from upper right corner to upper left etc

**Comment by RELNO** [comment]
@yasushisakai @guadalupebabio if you're there before I do, please pull this https://github.com/RELNO/CityScope_Scanner_Python/commit/6487e6465fe2276365bca6d655de6a869fb4c545 on C/H machine. Then, run `keystone.py` and as mentioned before, keystone from right to left.

**Comment by guadalupebabio** [comment]
I didn't know how to switch the scanner. I won't get to the lab until tomorrow

**Comment by yasushisakai** [comment]
@RELNO keystone.py demands numpy, should I pip it?

**Comment by RELNO** [comment]
try `pip3 install` etc. It is weird since scanner.py uses numpy as well.

**Comment by RELNO** [comment]
@yasushisakai I've just ssh into and ran it without seeing a missing numpy note

**Comment by yasushisakai** [comment]
Yep! This low hanging fruit was retrieved. (0-17) seems to recognize fine. (Although I could do a better job at calibration)
