### ISSUE TITLE
Grid value convention

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#90]
This convention has been discussed between different people at different level but it has not been documented any where. By quilcky looking at the UDPSender (made by @yasushisakai ) and reading between the line that there is still something wrong in the integration of the building in processing  I have the feeling that there is a misunderstanding here.

So here is the grid settings agreed for a while now between  Scanner and the Simulation (and supposedly by Unity).

In this picture imagine you are looking the table on a ladder this is the ordered grid you will see from the top
<img width="565" alt="screen shot 2018-11-19 at 10 38 23" src="https://user-images.githubusercontent.com/3928502/48698517-91bf3480-ebe7-11e8-8b4f-f537d4eb2562.png">

For the slider can someone confirm if value 0 is on the left of this picture? I think so it corresponds to the place where the slider reinit it self with the mechanical switch.

This picture has to move in the wiki once agreed

**Comment by popabczhang** [comment]
Last time when I check with Carson, we agreed that for slider, left should
be zero.

For the order of the buildings, last time when I check with Ariel, if my
understanding was correct, it is like this:
<img width="600" alt="image: grid order.jpg" src="https://raw.githubusercontent.com/popabczhang/3d_projection_mapping_unity/master/doc/181119_grid%20order.jpg">

I can check with both again today and update here.

**Comment by popabczhang** [comment]
<img width="600" alt="image: grid order.jpg" src="https://raw.githubusercontent.com/popabczhang/3d_projection_mapping_unity/master/doc/181119_grid%20order.jpg">

**Comment by yasushisakai** [comment]
It is just confirmation and consensus building, I assume this is not important implementation wise.

The scanner is now in sync with the diagram below.
![](https://user-images.githubusercontent.com/3928502/48698517-91bf3480-ebe7-11e8-8b4f-f537d4eb2562.png) this also relates to the the orientation of the camera.
![cam_orientation](https://user-images.githubusercontent.com/1502180/48717251-05ad0d00-ebe7-11e8-8b25-2be5218712db.jpg)
Note that the camera head is pointing the slider side.
As @agrignard  mentioned, @Carsonsmuts is this the case?

**We definitely want to tombstone this, we have lost two days of two to three brains.**

**Comment by agrignard** [comment]
Ok good to know because indeed this is what was discussed with a big part of the group for now almost one month (for the grid order)

We never agree with anyone with this https://raw.githubusercontent.com/popabczhang/3d_projection_mapping_unity/master/doc/181119_grid%20order.jpg

**Comment by agrignard** [comment]
Just to be sure what we agree is when you see the table from the top?Like  you are on the ladder, not from the ground?

**Comment by agrignard** [comment]
Ok great we are now on the same page with Processing and Scanning (the UDP Sender is also coherent) for the value of the slider it's fine.
See https://github.com/CityScope/CS_Cooper-Hewitt/issues/91

So let's close this issue as soon as this is documented in the wiki

**Comment by agrignard** [comment]
currently the scanner is sending a flip information in x
0,0 is 5,0, etc...

**Comment by agrignard** [comment]
merged in #75

**Comment by agrignard** [comment]
I just saw that is has been done by @guadalupebabio  in the wiki
https://github.com/CityScope/CS_Cooper-Hewitt/wiki/Table-Orientation

For the next time it can be good to close the corrseponding issue
