### ISSUE TITLE
UDP Sender broken with "Virtual" Slider

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Cooper-Hewitt#91]
How to reproduce it

1. Run UDPSender.pde
2. Run ABMoblity.pde
3. Press Send button in the UI

Reslults:
in JSONArray sliders = json.getJSONArray("slider"); we get the follwoing error
**JSONOBject["slider"] is not a JSONArray**

This is just a question of convention @yasushisakai can you coordinate with @RELNO to be sure that UDPSender is sending **EXACTLY** the same string. So we are sure that the emulator is doing exaclty the same job

**Comment by agrignard** [comment]
@RELNO to start the documentation process, (I cannot do it remotely), can you send in this issue
or even directly in the wiki
https://github.com/CityScope/CS_Cooper-Hewitt/wiki/Scanning 

The exact string that is sent by the scann (for instance when all the buildings are here (like the configuration on the picture))

**Comment by agrignard** [comment]
Fixed in https://github.com/CityScope/CS_Cooper-Hewitt/commit/77c946fa42f67c4ff15e23d78afaee55ae9cc327

Thanks @yasushisakai

**Comment by RELNO** [comment]
@agrignard this will consolidated intro wiki as soon as we're done dev and migrate the scanner as submodule.  For now, it's here: https://github.com/RELNO/CityScope_Scanner_Python/blob/master/README.md
