### ISSUE TITLE
Network disconnection

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#93]
8:42 found with the udp network connection broken.

Confirmed the following:
- scanner was working, from the master computer sliding values.
- simulation running.
- ping from slave to master was working (ssh too)
- was able to show to master
- both could and GPUram and CPU usage was low (almost nothing)
- **unity program movies were not playing**

Not sure if:
- unity have locked port?
  - tried to listen to 7777 from processing example sketch but no response.
- unity still alive, or hung?
- UDP connection dropped.

**Comment by agrignard** [comment]
IS this still an issue?

**Comment by agrignard** [comment]
Let's close this issue also (and reopen it if it happens)
