### ISSUE TITLE
Remove Special Building Interaction

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#94]
According to the meeting that we had with Kent, @LAAP and @yasushisakai.

# Current
Building Blocks 18-23 has special effects showing the following.

- collision potential
- glyphs vs colored dots
- network visibility

# Should
No interaction should occur when placing 18-23 blocks.

Invert of #46.

**Comment by agrignard** [comment]
done (interaction are not here anymore)
