### ISSUE TITLE
resolution improvement 

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#96]
@ooookai pointed out that the SCALE factor is configurable to 1.0 will add resolution to the simulation.

This will add GPU ram usage, since more pixels will be baked by the shader. Yet, the performance impact is low (untill ~2.0), adding the fact that we do not have the unity program running simultaneously. This value should be 1.0 for production.

This issue is for memorandum purposes. In the future we might consider this value should be applied to the ```playgroundWidth/Height``` values, since this defines the canvas size for keystoning.

scale: 0.5
![scale_0 5](https://user-images.githubusercontent.com/1502180/48872663-24163280-edb8-11e8-845a-6d71ab572c12.png)

scale: 1.0
![scale_1 0](https://user-images.githubusercontent.com/1502180/48872668-2a0c1380-edb8-11e8-9c79-7b2fb367dfae.png)

**Comment by LAAP** [comment]
For this deployment; since we have a dedicated computer for processing, we should go full-pixel-power.

**Comment by agrignard** [comment]
let's go for full scale then a new Keystone might be needed

**Comment by yasushisakai** [comment]
Got it, this will be incorporated in the next push.

**Comment by agrignard** [comment]
just one stuff, the speed need to bu updated according to the scale

**Comment by agrignard** [comment]
this can be considered as close in https://github.com/CityScope/CS_Cooper-Hewitt/commit/b8f590ae154f53f21c7397b2ebd6e40217cbd3dc
