### ISSUE TITLE
Grid Interaction needs to be drastic

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#99]
The last follow up meeting had another comment: normal interaction animation was too subtle.

Some ideas discussed.

0. Pumping up current "hair" effect
1. Agents spurring **a lot**
2. Wave / ripple effect
3. Other graphical effects

@yasushisakai does not have special feelings about using/trashing the current "hair" effect. This is a combination of design and implementation.

For time constrains, if we do not have any comments or agreement by friday morning, I will make it up. If *3. Other graphical effects*, please provide a example gif, clip or something we can see.

**Comment by RELNO** [comment]
Adding @Kent-Larson comment to the mix [I've no way to gif it though]:
Upon putting a new building in place, the entire simulation pauses and only the new agents/cars/pevs created by this building are spawning out and are merging into the paused environment. Then, after ~couple of seconds, the whole thing moves again. 
Concept: putting a building down makes a clear effect on the sim.

**Comment by agrignard** [comment]
@yasushisakai one way to add some interaction (not sure about the results if it looks cool or weird) could be to trigger in the GridInteractionAnimation draw function while isActive some boolean randomly like showBackground, showGlyphs, showNetwork, showAgent, showZombie, showCollisionPotential depending on the id of the building

Isolating only the agent involved with the building that has just been pushed and stopping (or not displaying would be easier) all the rest is also doable I am just a bit afraid we are tight in term of timing to test but we can try this week end in a bonus mode.

The idea could be to check in the draw function if a building has just been pushed (thourgh a boolean trigger during the isActive mode if this boolean is true we display only the agent whom R,O or A is equal to the building that has just been placed. It shouldn't be to greedy in term of computation

**Comment by agrignard** [comment]
Reagrding special effect in this commit https://github.com/CityScope/CS_Cooper-Hewitt/commit/cfb40696b91499a76b798894df6940dc2ef05e07 I just display in red the agent that are linked to the block moved. It s a starting point but the implentation is ok using the gridAnimation mechanism. We need to see how to make it more "wow" by playing with the transparency of the other, etc. It will be easier to iterate while seing the result on the table.

In this commit , the anim is not set to true not to break the current version, to test it set ````enableAnimationMode````


Also the potential issue that I can anticipate:
1. if there is a false detection, which is sometime happening now due to the fact that there is not constraint on the table (see issue #88), the wrong agent will be displayed
2. now it's also triggered when we remove a block (as if id=-1 was added) we need to isolate this case

I test it with the UDPSender emulator I think it will be different on the physical table.

**Comment by gabrielabila** [comment]
Hi! If it's still time to implement, my suggestions for the user feedback effects when moving blocks on the table are as follow on the image below. Apart from that, would be interesting to have:

- traffic jams and red heat maps at the crossings when too many (10+ ?) high buildings at the Bad World;
- tons of pedestrians crowding around the tower/pyramid.

*If these two are not possible to make with simulation, could we use .png images to forge this idea?

![ch_feedback effects_02](https://user-images.githubusercontent.com/42970128/48963170-de16c580-ef95-11e8-8b0f-137bea93cff8.jpg)

**Comment by agrignard** [comment]
variation in https://github.com/CityScope/CS_Cooper-Hewitt/commit/b3ad68da7e418eaac48e3d44d75b3a44ef1f5de8

Basic interaction spawning agent and showing only agent "linked" with the specific building. Same effect for every block 


<img width="756" alt="screen shot 2018-11-24 at 08 23 03" src="https://user-images.githubusercontent.com/3928502/48968934-76c43a00-efc4-11e8-9232-165d45569b8c.png">

TODO: 
1. Take in account the id of the block move (to test different rendering)
2. Differentiate bad vs good world rendering

**Comment by LAAP** [comment]
I like this effect. I like the difference between a tower and normal building from @gabrielabila and the implementation in wite from Arnaud. Maybe, we can use more or fewer lines depending on the density of the building, and the heatmaps are more related to special buildings. Also, a cool idea is that the effect it is wite at the good world and red in the bad world. So we have a difference in density, spetial buildings, and in good-bad worlds.

**Comment by agrignard** [comment]
We will review today the "drastic" interaction and decide wether or not we close this issue (or open a more dedicated one)

**Comment by agrignard** [comment]
Commit https://github.com/CityScope/CS_Cooper-Hewitt/commit/e1c01c8760316abcbd667cde1ded84fdf00219dc is a validated first iteration

see #86 for next step
